name: Notify Pages

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]
    branches: [ main, gh-pages ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo -n apt-get update && sudo -n apt-get install -y jq

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: gh-pages

      - name: Compute duration since build start
        id: dur
        shell: bash
        run: |
          if [ -f "__build_started_epoch.txt" ]; then
            START_TS=$(tr -d '\n\r' < __build_started_epoch.txt || echo "")
            if [ -n "$START_TS" ]; then
              NOW=$(date +%s)
              DURL=$(( NOW - START_TS ))
              DUR_MIN=$(( DURL / 60 ))
              echo "has_ts=true"      >> "$GITHUB_OUTPUT"
              echo "dur_min=$DUR_MIN" >> "$GITHUB_OUTPUT"
            else
              echo "has_ts=false"     >> "$GITHUB_OUTPUT"
            fi
          else
            echo "has_ts=false"       >> "$GITHUB_OUTPUT"
          fi

      - name: Send Discord (pages completed)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PAGES_URL_OVERRIDE:  ${{ secrets.PAGES_URL_OVERRIDE }}
        shell: bash
        run: |
          if [ -z "${DISCORD_WEBHOOK_URL:-}" ]; then
            echo "::warning::No DISCORD_WEBHOOK_URL secret set in external repo; skipping notify."
            exit 0
          fi
          STATUS="${{ github.event.workflow_run.conclusion }}"
          EMOJI=$([ "$STATUS" = "success" ] && echo "✅" || echo "❌")
          URL="${PAGES_URL_OVERRIDE:-https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/}"

          if [ "${{ steps.dur.outputs.has_ts }}" = "true" ]; then
            MSG="$EMOJI Pages deployment $STATUS (소요 ${{ steps.dur.outputs.dur_min }}분)\n🔗 ${URL}"
          else
            MSG="$EMOJI Pages deployment $STATUS\n🔗 ${URL}"
          fi

          PAYLOAD=$(jq -Rn --arg c "$MSG" '{content:$c}')
          curl -sS -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL" || true
